export const departments = [
    "Computer Science and Engineering",
    "Information Science and Engineering",
    "Mechanical Engineering",
    "Civil Engineering",
    "Electrical and Electronics Engineering",
    "Electronics and Communication Engineering",
    "Aerospace Engineering",
    "Automobile Engineering",
    "Chemical Engineering",
    "Biotechnology Engineering",
    "Industrial and Production Engineering",
    "Instrumentation Technology",
    "Mechatronics Engineering",
    "Telecommunication Engineering",
    "Environmental Engineering",
    "Mining Engineering",
    "Textile Technology",
    "Biomedical Engineering",
    "Agricultural Engineering",
    "Artificial Intelligence and Machine Learning",
    "Robotics and Automation",
    "Data Science",
    "Cyber Security"
  ];
  